# Generated by Django 4.2.23 on 2025-10-14 20:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveuniverse', '0011_extend_industry_activites'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access reactions app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_type_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('time_seconds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ReactionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('allowed_group_ids', models.JSONField(default=list)),
                ('refine_rate', models.DecimalField(decimal_places=4, default=Decimal('0.8000'), max_digits=5)),
                ('price_basis', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EveTypePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('sell', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('buy_average', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('sell_average', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('eve_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aareactions_price', to='eveuniverse.evetype')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='aareactions.reaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eveuniverse.evetype')),
            ],
            options={
                'unique_together': {('reaction', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ReactionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='aareactions.reaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eveuniverse.evetype')),
            ],
            options={
                'unique_together': {('reaction', 'type')},
            },
        ),
    ]
