# Generated by Django 4.2.23 on 2025-10-17 16:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aareactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access reactions app'), ('reactions_admin', 'Can manage default reaction setting'))},
        ),
        migrations.RenameField(
            model_name='reactionsettings',
            old_name='price_basis',
            new_name='output_price_basis',
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='accounting_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='broker_fee_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='cost_index_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.150'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='facility_location',
            field=models.CharField(choices=[('low', 'Low'), ('null', 'Null'), ('wh', 'WH')], default='low', max_length=8),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='facility_size',
            field=models.CharField(choices=[('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=8),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='facility_tax_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='input_price_basis',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=8),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='reaction_skill_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='rig_me',
            field=models.CharField(choices=[('none', 'None'), ('t1', 'T1 ME'), ('t2', 'T2 ME')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='rig_te',
            field=models.CharField(choices=[('none', 'None'), ('t1', 'T1 TE'), ('t2', 'T2 TE')], default='none', max_length=8),
        ),
        migrations.AlterField(
            model_name='reactionsettings',
            name='refine_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=6),
        ),
    ]
