# Generated by Django 4.2.23 on 2025-10-22 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aareactions', '0002_alter_general_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionsettings',
            name='scrap_metal_processing_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
