# Generated by Django 4.2.23 on 2025-10-30 14:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aareactions', '0003_reactionsettings_scrap_metal_processing_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionsettings',
            name='buyback_basis',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=8),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='buyback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reactionsettings',
            name='buyback_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
