# Generated by Django 4.2.25 on 2026-06-03 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aareactions', '0005_systemindices_reactionsettings_refine_implant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterstandings',
            name='standing',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
