# Generated by Django 4.2.25 on 2026-06-04 00:00

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("aareactions", "0006_alter_characterstandings_standing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReactionSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("refine_rate", models.DecimalField(decimal_places=2, default=Decimal("80.00"), max_digits=6)),
                ("input_price_basis", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=8)),
                ("output_price_basis", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], default="sell", max_length=8)),
                ("broker_fee_pct", models.DecimalField(decimal_places=2, default=Decimal("3.00"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("accounting_level", models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("reaction_skill_level", models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("facility_size", models.CharField(choices=[("medium", "Medium"), ("large", "Large")], default="medium", max_length=8)),
                ("facility_location", models.CharField(choices=[("low", "Low"), ("null", "Null"), ("wh", "WH")], default="low", max_length=8)),
                ("rig_me", models.CharField(choices=[("none", "None"), ("t1", "T1 ME"), ("t2", "T2 ME")], default="none", max_length=8)),
                ("rig_te", models.CharField(choices=[("none", "None"), ("t1", "T1 TE"), ("t2", "T2 TE")], default="none", max_length=8)),
                ("facility_tax_pct", models.DecimalField(decimal_places=2, default=Decimal("1.50"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("cost_index_pct", models.DecimalField(decimal_places=3, default=Decimal("0.150"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("scrap_metal_processing_level", models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("solar_system_id", models.IntegerField(blank=True, null=True)),
                ("everef_structure_type_id", models.IntegerField(blank=True, null=True)),
                ("everef_rig_ids", models.CharField(blank=True, default="", max_length=255)),
                ("advanced_industry_level", models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("system_cost_bonus_pct", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("everef_material_prices", models.CharField(blank=True, default="", max_length=64)),
                ("alpha_clone", models.BooleanField(default=False)),
                ("use_buyback_for_stock", models.BooleanField(default=False)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="aareactions_settings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User Reaction Settings",
                "verbose_name_plural": "User Reaction Settings",
                "default_permissions": (),
            },
        ),
    ]
